version: "3.9"
services:
  backend:
    build: ./backend
    container_name: datapilot-backend
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: datapilot-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
