services:
  backend_features:
    build: .
    container_name: backend_features
    ports:
      - "4000:4000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/excel"]
      interval: 20s
      timeout: 5s
      retries: 5
    restart: unless-stopped
